int _putchar(char c);
int _strlen_recursion(char *s);
int factorial(int n);
int _pow_recursion(int x, int y);
int _sqrt(int n, int i);
int _sqrt_recursion(int n);
int _prime(int n, int i);
int is_prime_number(int n);
void _print_rev_recursion(char *s);
void _puts_recursion(char *s);
int is_palindrome(char *s);
int _compare(char *s, int n1, int n2);
int _strlen(char *s);
int wildcmp(char *s1, char *s2);
